FROM tensorflow/tensorflow:latest-py3
ADD . /developer
LABEL maintainer="kenakamu@microsoft.com"

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
EXPOSE 80
CMD [ "python", "./my.py" ]